services:

  rabbitmq:
    image: rabbitmq:4-management
    container_name: iot-rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10


  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.159.0
    container_name: iot-otel-collector
    restart: unless-stopped

    command:
      - "--config=/etc/otelcol-contrib/config.yaml"

    volumes:
      - ./infra/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro

    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"

    depends_on:
        - tempo
        - loki


  ingestion-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: iot-ingestion-api
    restart: unless-stopped

    environment:
      APP_NAME: ingestion-api

      PORT: "3001"

      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318

    ports:
      - "3001:3001"

    depends_on:
      rabbitmq:
        condition: service_healthy

      otel-collector:
        condition: service_started

    healthcheck:
        test:
            [
            "CMD",
            "node",
            "-e",
            "fetch('http://127.0.0.1:3001/health').then(r => { if (!r.ok) process.exit(1) }).catch(() => process.exit(1))"
            ]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 10s


  telemetry-worker:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: iot-telemetry-worker
    restart: unless-stopped

    environment:
      APP_NAME: telemetry-worker

      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318

      LOG_LEVEL: info

    depends_on:
      rabbitmq:
        condition: service_healthy

      otel-collector:
        condition: service_started


  anomaly-worker:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: iot-anomaly-worker
    restart: unless-stopped

    environment:
      APP_NAME: anomaly-worker

      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318

      LOG_LEVEL: info

    depends_on:
      rabbitmq:
        condition: service_healthy

      otel-collector:
        condition: service_started


  alert-worker:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: iot-alert-worker
    restart: unless-stopped

    environment:
      APP_NAME: alert-worker

      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318

      LOG_LEVEL: info

    depends_on:
      rabbitmq:
        condition: service_healthy

      otel-collector:
        condition: service_started


  device-simulator:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: iot-device-simulator
    restart: unless-stopped

    environment:
      APP_NAME: device-simulator

      INGESTION_API_URL: http://ingestion-api:3001

      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318

    depends_on:
      ingestion-api:
        condition: service_healthy

  tempo:
    image: grafana/tempo:2.10.7
    container_name: iot-tempo
    restart: unless-stopped

    command:
      - "-config.file=/etc/tempo.yaml"

    volumes:
      - ./infra/tempo/tempo.yaml:/etc/tempo.yaml:ro
      - tempo_data:/var/tempo

    ports:
      - "3200:3200"


  prometheus:
    image: prom/prometheus:v3.14.0
    container_name: iot-prometheus
    restart: unless-stopped

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-remote-write-receiver"

    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

    ports:
      - "9090:9090"

    depends_on:
      - otel-collector


  loki:
    image: grafana/loki:3.7.6
    container_name: iot-loki
    restart: unless-stopped

    command:
      - "-config.file=/etc/loki/local-config.yaml"

    volumes:
      - ./infra/loki/loki.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki

    ports:
      - "3100:3100"


  grafana:
    image: grafana/grafana:13.1.3
    container_name: iot-grafana
    restart: unless-stopped

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    volumes:
      - grafana_data:/var/lib/grafana

      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards:ro

    ports:
      - "3000:3000"

    depends_on:
      - prometheus
      - tempo
      - loki

volumes:

  rabbitmq_data:

  tempo_data:

  prometheus_data:

  loki_data:

  grafana_data: